### ISSUE TITLE
Ottenere i modelli dopo la scelta di un make

### ISSUE THREAD

**Issue by andrea-css** [andrea-css/car-comparator#1]
Buongiorno, mi trovo a preparare l'esame ma mi sono fermato quando devo inserire i nomi dei modelli auto in base a Make... Potrebbe darmi qualche indicazione per andare avanti? Grazie

**Comment by jenkin** [comment]
Questa è la strategia: alla selezione del make devi inviare una nuova richiesta alle API (`$.getJSON(...)`) per ottenere i modelli relativi al make scelto.

In particolare devi interrogare l'[endpoint getModels](http://www.carqueryapi.com/documentation/api-usage/): https://www.carqueryapi.com/api/0.3/?callback=?&cmd=getModels&make=[make_selezionato].

Nella callback di questa richiesta devi creare le voci nel dropdown "models-menu", esattamente come hai già fatto per le altre dropdown.

**Comment by jenkin** [comment]
Ah, leggendo meglio la documentazione delle API mi sono accorto che ti sei complicato la vita... :open_mouth:

Praticamente getMakes ti fornisce l'elenco dei make e delle country (primo e secondo dropdown), getModels ti fornisce l'elenco dei modelli (terzo dropdown) come ti ho scritto nel commento precedente, ma poi devi fare altre due chiamate per avere i dettagli di un modello (perché per ogni modello esistono tante varianti!): prima a getTrims (che non fai scegliere all'utente, altrimenti dovresti aggiungere un quarto dropdown) e poi a getModel (da cui prendi i dati per mostrare la tabella delle specifiche).

Qui trovi un mio esempio funzionante (che poi replica [le demo](http://www.carqueryapi.com/demo/) che offrono direttamente i tipi dell'API): https://jenkin.github.io/car-comparator/index.html. Il [codice lo trovi qui](https://github.com/jenkin/car-comparator/tree/gh-pages), tenendo conto che ho fatto un po' di refactoring per leggerlo meglio (ho modificato API.js e index.html).

Se hai difficoltà a capire dove mettere le mani, fammi sapere... :+1:

**Comment by andrea-css** [comment]
Grazie ora mi rimetto al lavoro ! grazie dei commenti almeno riesco a capire meglio ;)

**Comment by andrea-css** [comment]
allora... ho pushato, come dovrei procedere per creare la lista una volta fatta la domanda a trims e model? grazie

**Comment by andrea-css** [comment]
Buonasera prof! posso avere la sua email, devo chiederle una mano? grazie

**Comment by jenkin** [comment]
Ci eri quasi, semplicemente stampavi in pagina le informazioni relative al singolo modello in un contenitore aggiuntivo sbagliato, mentre devono apparire nello stesso contenitore `.model-container` associato al filtro su cui agisce l'utente. L'ultimo mio commit dovrebbe funzionare, esattamente come abbiamo visto insieme all'esame.
