### ISSUE TITLE
I dropdown buttons non funzionano

### ISSUE THREAD

**Issue by andrea-css** [andrea-css/car-comparator#2]
Buongiorno, mi trovo a preparare l'esame ma mi sono fermato quando devo inserire i nomi dei modelli (model) auto in base a Make(CASA di fabbricazione... Potrebbe darmi qualche indicazione per andare avanti? Grazie.

**Comment by andrea-css** [comment]
tra l'altro sto cercando di andare avanti ma mi si crea un div sconosciuto...

**Comment by jenkin** [comment]
Issue risolta nella pull request https://github.com/andrea-css/car-comparator/pull/3
