### ISSUE TITLE
Allineare opportunamente i filtri / i dati dei modelli

### ISSUE THREAD

**Issue by jenkin** [andrea-css/car-comparator#4]
Devono essere uno accanto all'altro (due `-col-6` per esempio) e non certo uno sotto l'altro.

**Comment by andrea-css** [comment]
filtri allineati ma una volta fatta la prima selezione (selection1) mi partono i risultati sia nella prima e sia nella seconda colonna (il risultato viene scritto in nero sotto selection2)
